services:
  db:    
    container_name: db
    build: ./db
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data:/var/lib/mysql      
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u","vault","-pvault","-h", "localhost"]
      timeout: 30s
      retries: 10

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - ./vault/config:/vault/config
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK    
    environment:
      VAULT_ADDR : http://127.0.0.1:8200
      VAULT_API_ADDR : http://127.0.0.1:8200
      VAULT_ADDRESS : http://127.0.0.1:8200      
    entrypoint: vault server -config /vault/config/config.hcl
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_db_data:
